site_name: CDK Python Project
site_description: CDK Python Project
site_author: Randy Ridgley
repo_url: {{cookiecutter.git_repo_url}}
edit_uri: edit/main/docs

nav:
  - Homepage: index.md
  - Getting Started: getting_started.md
  - CDK: cdk.md
  - Pipeline: pipeline.md
  - Best Practices:
      - best_practices/logger.md
      - best_practices/tracer.md
      - best_practices/metrics.md
      - best_practices/environment_variables.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  logo: media/builder.png
  favicon: media/favicon.png

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2024 {{cookiecutter.author}}

plugins:
  - git-revision-date
  - search
extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-VN803S5YZ3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/randyridgley/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/randyridgley
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randyridgley/
